---
title: 'PGSW simplism / populism factor analysis: CAPI'
output:
  html_document:
    df_print: paged
  word_document: default
  html_notebook: default
  pdf_document: default
  code_folding: hide
---

```{r echo = F, eval = T, include=F}
load("PGSW2019.RData")
library(tidyverse); library(parameters); library(ggeffects); library(rio); library(scales); library(sjlabelled); library(labelled); library(sjPlot);
library(FactoMineR); library(psych); library(kableExtra)

S1_1 <- as.numeric(unlist(pgsw2019$simp_1)) %>%
  set_label("Politycy zamiast skutecznie działać ciągle gmatwają proste sprawy.")
S1_2 <- as.numeric(unlist(pgsw2019$simp_2)) %>%
  set_label("Naukowcy i eksperci różnych dziedzin zbytnio komplikują sprawy, które są dość proste.")
S1_3 <- as.numeric(unlist(pgsw2019$simp_3)) %>%
  set_label("Obecnie medycyna zamiast pomagać tylko mąci ludziom w głowach; by być zdrowym wystarczy żyć naturalnie i słuchać ludzi podobnych do nas.")
S1_4 <- as.numeric(unlist(pgsw2019$simp_4)) %>%
  set_label("Rozwiązanie problemów naszego kraju jest bardzo prostą rzeczą, trzeba tylko dać władze tym, którzy będą chcieli tego dokonać.")
S1_5 <- as.numeric(unlist(pgsw2019$simp_5)) %>%
  set_label("Prace parlamentu to niekończące się debatowanie nad szczegółami ustaw, a tymczasem regulacje niektórych spraw są tak proste, że każdy z nas mógłby je rozwiązać.")
S1_6 <- as.numeric(unlist(pgsw2019$simp_6)) %>%
  set_label("W polityce toczy się ostra walka między dobrem, reprezentowanym przez zwykłych ludzi, a złem – wynikającym z działań często skorumpowanych elit.")

P12_1 <- as.numeric(unlist(pgsw2019$neword)) %>%
  set_label("Polsce potrzebny jest ktoś, kto będzie miał dość siły, by zmienić całkowicie nasz system władzy i zaprowadzić nowy, sprawiedliwy ład i porządek.")
P12_2 <- as.numeric(unlist(pgsw2019$ordpeop)) %>%
  set_label("W Polsce nieliczni zawłaszczają władzę, przynależną zwykłym ludziom.")
P12_3 <- as.numeric(unlist(pgsw2019$crisis)) %>%
  set_label("Jest ostatnia chwila, by uchronić Polskę przed grożącą katastrofą.")
P12_4 <- as.numeric(unlist(pgsw2019$morals)) %>%
  set_label("W Polsce nic się nie poprawi, dopóki politycy nie powrócą do starych, dobrych wartości moralnych.")
P12_5 <- as.numeric(unlist(pgsw2019$simple)) %>%
  set_label("Rozwiązanie problemów naszego kraju jest bardzo prostą rzeczą, trzeba tylko dać władzę tym, którzy będą chcieli tego dokonać.")
P12_6 <- as.numeric(unlist(pgsw2019$goodev)) %>%
  set_label("Wszystko w polityce jest jednoznacznie dobre lub złe, wybór jest jasny.")

weight <- as.numeric(unlist(pgsw2019$weight))
popsimp <- data.frame(S1_1, S1_2, S1_3, S1_4, S1_5, S1_6,
                      P12_1, P12_2, P12_3, P12_4, P12_5, P12_6)
varlab <- get_label(popsimp)
```

```{r echo=F}
scree(popsimp)
```

```{r echo=F}
poly_model <- fa(popsimp, nfactor=3, cor="poly", fm="ml", rotate = "varimax", correct=0, n.obs=2003, weight=weight)
options(knitr.kable.NA = '')
kable(parameters(poly_model, threshold=0.3, labels=varlab, format="latex", booktabs=TRUE), digits=2) %>%
  kable_styling(latex_options="scale_down")
```

```{r echo=F}
factor.groups <- sjt.fa(popsimp, nmbr.fctr = 3)$factor.index
labs <- get_labels(pgsw2019$simp_1)
plot_likert(popsimp, groups=factor.groups, catcount=5, 
                           sort.frq="pos.asc", reverse.scale = TRUE,
                           legend.labels = labs)
```

